# Generated by Django 4.2.5 on 2023-10-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('caloriesNoExercise', models.FloatField()),
                ('caloriesExercise1to3', models.FloatField()),
                ('caloriesExercise4to6', models.FloatField()),
                ('caloriesExerciseDaily', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),  
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField(max_length=250)),
                ('weight', models.IntegerField(max_length=150)),
                ('food_allergies', models.CharField(max_length=200)),
                ('calories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.calories')),
            ],
        ),
    ]
