# Generated by Django 4.2.5 on 2023-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Category_Exercise', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Category_Food', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Information_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('food_allergies', models.CharField(max_length=200)),
                ('timeExercise', models.IntegerField()),
                ('calories', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='calories',
        ),
        migrations.DeleteModel(
            name='Calories',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
