# Generated by Django 4.2.5 on 2023-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_exercise_food_information_user_remove_user_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_user',
            name='timeExercise',
        ),
        migrations.AddField(
            model_name='information_user',
            name='body_condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='information_user',
            name='time_exercise_day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='information_user',
            name='time_exercise_week',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Exercise_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='food_allergies',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
