# Generated by Django 4.2.5 on 2023-11-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_information_user_timeexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_user',
            name='category_exercise',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='information_user',
            name='category_food',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
