# Generated by Django 4.2.5 on 2023-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_information_user_category_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_user',
            name='category_exercise',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information_user',
            name='category_food',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
