# Generated by Django 4.2.5 on 2023-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_information_user_category_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_user',
            name='target',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
