# Generated by Django 4.2.5 on 2023-12-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_information_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_user',
            name='category_exercise',
        ),
        migrations.RemoveField(
            model_name='information_user',
            name='category_food',
        ),
        migrations.RemoveField(
            model_name='information_user',
            name='food_allergies',
        ),
    ]
