# Generated by Django 4.2.5 on 2023-12-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_information_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_user',
            name='name',
        ),
    ]
